config/routes.rb
MiniVmail::Application.routes.draw do
	
	get "downloads" => 'downloads#index' 

	get "downloads/export_relay_domains"
	get "downloads/virtual_aliases"
	get "downloads/relay_domains"
	get "downloads/relay_recipients"
	get "downloads/dovecot_auth"

	match "login" => 'user_sessions#new', :as => :login
	match "logout" => 'user_sessions#destroy', :as => :logout

	resource :user_session
	resources :users
	resources :forwards
	resources :mailboxes
	resources :domains

	get "welcome/index"
	get "welcome/initial_login"
	post "welcome/create_initial_login"

	root :to => "welcome#index"

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :mailboxes, :inverse_of => :domain
  has_many :forwards, :inverse_of => :domain
  
  attr_accessible :name, :transport, :notes, :active

  validates :name, :presence => true, :uniqueness => true
  validates_presence_of :transport
  
  scope :active, where(:active => true)
  scope :ordered, order("domains.active DESC, domains.name ASC")
  scope :name_like, lambda { |name| where("domains.name LIKE ?", "%#{name}%") } 

  def self.search(params={})
    scope=scoped
    scope = scope.name_like(params[:name_like]) unless params[:name_like].blank?
    scope.ordered
  end
  
  def to_s
    name
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  respond_to :html,:xml,:json
  before_filter :require_admin, :except => [:index,:show]
  before_filter :require_user, :only => [:index,:show]
  
  def index
    @domains = Domain.search(params)
    respond_with @domains
  end
  
  def show
    @domain = Domain.find(params[:id])
    respond_with @domain
  end
  
  def new
    @domain = Domain.new
    @domain.transport = APP_CONFIG[:relay_transport]
    @domain.active =true
    respond_with @domain
  end
  
  def create
    @domain = Domain.new(params[:domain])
    set_modificator @domain
    flash[:notice] = I18n.t(:'resource.created', :model=> Domain.model_name.human) if @domain.save
    respond_with @domain  
  end
  
  def edit
    @domain = Domain.find(params[:id])
    respond_with @domain
  end
  
  def update
    @domain = Domain.find(params[:id])
    set_modificator @domain
    flash[:notice] = I18n.t(:'resource.updated', :model=> Domain.model_name.human) if @domain.update_attributes(params[:domain])
    respond_with @domain  
  end
  
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy
    flash[:notice] = I18n.t(:'resource.destroyed', :model=> Domain.model_name.human)
    respond_with @domain
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for @domain do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :transport %><br />
    <%= f.text_field :transport %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/domains/edit.html.erb
<% title t(:'resource.edit', :model => Domain.model_name.human) %>

<%= render 'form' %>

<p class="actions">
  <%= link_to t(:'actions.show'), @domain %> |
  <%= link_to t(:'title.domains'), domains_path %>
</p>

app/views/domains/index.html.erb
<% title t(:'title.domains') %>

<table>
  <thead>
  <tr>
    <th><%= Domain.human_attribute_name("name") %></th>
    <th><%= Domain.human_attribute_name("active") %></th>
    <th><%= Domain.human_attribute_name("created_by") %></th>
    <th><%= Domain.human_attribute_name("updated_by") %></th>
  </tr>
  </thead>
  <tbody>
  <% for domain in @domains %>
    <tr>
      <td><%= link_to domain.name, domain %></td>
      <td><%= domain.active %></td>
      <td><%= domain.created_by %></td>
      <td><%= domain.updated_by %></td>
      <td class="actions"><%= link_to t(:'actions.edit'), edit_domain_path(domain) %></td>
      <td class="actions"><%= link_to t(:'actions.delete'), domain, :confirm => t(:'actions.confirmdelete'), :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p class="actions"><%= link_to t(:'resource.new', :model => Domain.model_name.human), new_domain_path %></p>

app/views/domains/new.html.erb
<% title t(:'resource.new', :model => Domain.model_name.human) %>

<%= render 'form' %>

<p class="actions"><%= link_to t(:'title.domains'), domains_path %></p>

app/views/domains/show.html.erb
<% title Domain.model_name.human %>

<p>
  <strong><%= Domain.human_attribute_name("name") %>:</strong>
  <%= @domain.name %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("transport") %>:</strong>
  <%= @domain.transport %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("notes") %>:</strong>
  <%= @domain.notes %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("active") %>:</strong>
  <%= @domain.active %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("created_by") %>:</strong>
  <%= @domain.created_by %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("created_at") %>:</strong>
  <%= l(@domain.created_at, :format => :short) %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("updated_by") %>:</strong>
  <%= @domain.updated_by %>
</p>
<p>
  <strong><%= Domain.human_attribute_name("updated_at") %>:</strong>
  <%= l(@domain.updated_at, :format => :short) %>
</p>

<p class="actions">
  <%= link_to t(:'actions.edit'), edit_domain_path(@domain) %> |
  <%= link_to t(:'actions.delete'), @domain, :confirm => t(:'actions.confirmdelete'), :method => :delete %> |
  <%= link_to t(:'title.domains'), domains_path %>
</p>