config/routes.rb
MiniVmail::Application.routes.draw do
	
	get "downloads" => 'downloads#index' 

	get "downloads/export_relay_domains"
	get "downloads/virtual_aliases"
	get "downloads/relay_domains"
	get "downloads/relay_recipients"
	get "downloads/dovecot_auth"

	match "login" => 'user_sessions#new', :as => :login
	match "logout" => 'user_sessions#destroy', :as => :logout

	resource :user_session
	resources :users
	resources :forwards
	resources :mailboxes
	resources :domains

	get "welcome/index"
	get "welcome/initial_login"
	post "welcome/create_initial_login"

	root :to => "welcome#index"

end

app/models/forward.rb
class Forward < ActiveRecord::Base
  belongs_to :domain, :inverse_of => :forwards
  
  attr_accessible :name, :domain_id, :notes, :active, :destination
  
  before_validation(:if => :destination_changed?) {|forward| forward.destination=forward.destination}
  
  validates_presence_of :name, :domain, :destination
  
  scope :active, where(:active => true)
  scope :ordered, order("forwards.active DESC, forwards.name ASC")
  scope :domain_id, lambda { |domain_id| where(:domain_id => domain_id)}
  scope :name_like, lambda { |name| where("forwards.name LIKE ?", "%#{name}%") } 
  
  def self.search(params={})
     scope = includes(:domain)
     scope = scope.name_like(params[:name_like]) unless params[:name_like].blank?
     scope = scope.domain_id(params[:domain_id]) unless params[:domain_id].blank?
     scope.ordered
   end
  

  def to_s
    domain ? "#{name}@#{domain}" : name
  end
  
  def name=(name)
    name = name.downcase unless name.blank?
    write_attribute :name, name
  end
  
  def destination=(dest)
    dest = dest + '@' + domain.name unless (domain.blank? || dest =~ /@/) 
    write_attribute :destination, dest
  end
end

app/controllers/forwards_controller.rb
require 'pagination_responder'

class ForwardsController < ApplicationController
  respond_to :html,:xml,:json
  before_filter :require_user
  before_filter :set_select_domains, :only => [:new, :create, :edit, :update, :index]

  def index
    @forwards = Forward.search params
    respond_with @forwards, :responder => PaginationResponder
  end
  
  def show
    @forward = Forward.find(params[:id])
    respond_with @forward
  end
  
  def new
    @forward = Forward.new
    @forward.active = true
    respond_with @forward
  end
  
  def create
    @forward = Forward.new(params[:forward])
    set_modificator @forward
    flash[:notice] = I18n.t(:'resource.created', :model=> Forward.model_name.human) if @forward.save
    respond_with @forward
  end
  
  def edit
    @forward = Forward.find(params[:id])
    respond_with @forward
  end
  
  def update
    @forward = Forward.find(params[:id])
    set_modificator @forward
    flash[:notice] = I18n.t(:'resource.updated', :model=> Forward.model_name.human) if @forward.update_attributes(params[:forward])
    respond_with @forward
  end
  
  def destroy
    @forward = Forward.find(params[:id])
    @forward.destroy
    flash[:notice] = I18n.t(:'resource.destroyed', :model=> Forward.model_name.human)
    respond_with @forward
  end
end

app/helpers/forwards_helper.rb
module ForwardsHelper
end

app/views/forwards/_form.html.erb
<%= form_for @forward do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :domain %><br />
    <%= f.collection_select :domain_id, @domains, :id, :name %>
  </p>
  <p>
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/forwards/edit.html.erb
<% title t(:'resource.edit', :model => Forward.model_name.human) %>

<%= render 'form' %>

<p class="actions">
  <%= link_to t(:'actions.show'), @forward %> |
  <%= link_to t(:'title.forwards'), forwards_path %>
</p>

app/views/forwards/index.html.erb
<% title t(:'title.forwards') %>
<%= render :partial => 'shared/search_form', :locals => { :domains => @domains, :target_url => forwards_path } %>
<%= paginate @forwards %>
<table>
  <thead>	
  <tr>
    <th><%= Forward.human_attribute_name("name") %></th>
    <th><%= Forward.human_attribute_name("destination") %></th>
    <th><%= Forward.human_attribute_name("active") %></th>
    <th><%= Forward.human_attribute_name("created_by") %></th>
    <th><%= Forward.human_attribute_name("updated_by") %></th>
  </tr>
  </thead>
  <tbody>	
  <% for forward in @forwards %>
    <tr>
      <td><%= link_to forward, forward %></td>
      <td><%= forward.destination %></td>
      <td><%= forward.active %></td>
      <td><%= forward.created_by %></td>
      <td><%= forward.updated_by %></td>
      <td class="actions"><%= link_to t(:'actions.edit'), edit_forward_path(forward) %></td>
      <td class="actions"><%= link_to t(:'actions.delete'), forward, :confirm => t(:'actions.confirmdelete'), :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @forwards %>
<p class="actions"><%= link_to t(:'resource.new', :model => Forward.model_name.human), new_forward_path %></p>

app/views/forwards/new.html.erb
<% title t(:'resource.new', :model => Forward.model_name.human) %>

<%= render 'form' %>

<p class="actions"><%= link_to t(:'title.forwards'), forwards_path %></p>

app/views/forwards/show.html.erb
<% title Forward.model_name.human %>

<p>
  <strong><%= Forward.human_attribute_name("name") %>:</strong>
  <%= @forward.name %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("destination") %>:</strong>
  <%= @forward.destination %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("domain") %>:</strong>
  <%= @forward.domain %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("active") %>:</strong>
  <%= @forward.active %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("notes") %>:</strong>
  <%= @forward.notes %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("created_by") %>:</strong>
  <%= @forward.created_by %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("created_at") %>:</strong>
  <%= l(@forward.created_at, :format => :short) %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("updated_by") %>:</strong>
  <%= @forward.updated_by %>
</p>
<p>
  <strong><%= Forward.human_attribute_name("updated_at") %>:</strong>
  <%= l(@forward.updated_at, :format => :short) %>
</p>

<p class="actions">
  <%= link_to t(:'actions.edit'), edit_forward_path(@forward) %> |
  <%= link_to t(:'actions.delete'), @forward, :confirm =>  t(:'actions.confirmdelete'), :method => :delete %> |
  <%= link_to t(:'title.forwards'), forwards_path %>
</p>