config/routes.rb
MiniVmail::Application.routes.draw do
	
	get "downloads" => 'downloads#index' 

	get "downloads/export_relay_domains"
	get "downloads/virtual_aliases"
	get "downloads/relay_domains"
	get "downloads/relay_recipients"
	get "downloads/dovecot_auth"

	match "login" => 'user_sessions#new', :as => :login
	match "logout" => 'user_sessions#destroy', :as => :logout

	resource :user_session
	resources :users
	resources :forwards
	resources :mailboxes
	resources :domains

	get "welcome/index"
	get "welcome/initial_login"
	post "welcome/create_initial_login"

	root :to => "welcome#index"

end

app/models/mailbox.rb
class Mailbox < ActiveRecord::Base
  belongs_to :domain, :inverse_of => :mailboxes
  scope :active, where(:active => true)
  scope :ordered, order("mailboxes.active DESC, mailboxes.name ASC")
  scope :domain_id, lambda { |domain_id| where(:domain_id => domain_id)}
  scope :name_like, lambda { |name| where("mailboxes.name LIKE ?", "%#{name}%") } 
  
  validates_presence_of :name, :password, :domain
  validates_uniqueness_of :name, :scope => :domain_id
  validates_confirmation_of :my_password
  validates :name, :format => { :with => /\A([^@\s]+)\z/}
  
  attr_accessible :name, :domain_id, :notes, :active, :my_password, :my_password_confirmation
  
  attr_reader :my_password
  
  def self.search(params={})
    scope = includes(:domain)
    scope = scope.name_like(params[:name_like]) unless params[:name_like].blank?
    scope = scope.domain_id(params[:domain_id]) unless params[:domain_id].blank?
    scope.ordered
  end
  
  def my_password=(pass)
    @my_password=pass
    self.password=pass unless pass.blank?
  end
  
  def name=(name)
    name = name.downcase unless name.blank?
    write_attribute :name, name
  end
  
  def to_s
    domain ? "#{name}@#{domain}" : name
  end

  def as_json(options)
    super(serialize_opts(options))
  end
  
  def to_xml(options)
    super(serialize_opts(options))
  end
    
  private
  def serialize_opts(options={})
    options[:except]=[:password]
    logger.debug options
    options    
  end
end

app/controllers/mailboxes_controller.rb
require 'pagination_responder'

class MailboxesController < ApplicationController
  respond_to :html,:xml,:json
  before_filter :require_user
  before_filter :set_select_domains, :only => [:new, :create, :edit, :update, :index]
  
  def index
    @mailboxes = Mailbox.search(params)
    respond_with @mailboxes, :responder => PaginationResponder
  end
  
  def show
    @mailbox = Mailbox.find(params[:id])
    respond_with @mailbox
  end
  
  def new
    @mailbox = Mailbox.new
    @mailbox.active = true
    serialize_opts = {:only => [:name, :domain_id, :active,:notes], :methods=>[:my_password,:my_password_confirmation]} 
    respond_with @mailbox do |format|
      format.json { render :json => @mailbox.as_json(serialize_opts)}
      format.xml { render :xml => @mailbox.to_xml(serialize_opts)}
    end
  end
  
  def create
    @mailbox = Mailbox.new(params[:mailbox])
    set_modificator @mailbox
    flash[:notice] = I18n.t(:'resource.created', :model=> Mailbox.model_name.human) if @mailbox.save
    respond_with @mailbox
   end
  
  def edit
    @mailbox = Mailbox.find(params[:id])
    respond_with @mailbox
  end
  
  def update
    @mailbox = Mailbox.find(params[:id])
    set_modificator @mailbox
    flash[:notice] = I18n.t(:'resource.updated', :model=> Mailbox.model_name.human) if @mailbox.update_attributes(params[:mailbox])
    respond_with @mailbox
  end
  
  def destroy
    @mailbox = Mailbox.find(params[:id])
    @mailbox.destroy
    flash[:notice] = I18n.t(:'resource.destroyed', :model=> Mailbox.model_name.human)
    respond_with @mailbox
  end
  
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<%= form_for @mailbox do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :domain %><br />
    <%= f.collection_select :domain_id, @domains, :id, :name %>
  </p>
  <p>
    <%= f.label :my_password %><br />
    <%= f.password_field :my_password %>
  </p>
  <p>
    <%= f.label :my_password_confirmation %><br />
    <%= f.password_field :my_password_confirmation %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/mailboxes/edit.html.erb
<% title t(:'resource.edit', :model => Mailbox.model_name.human) %>

<%= render 'form' %>

<p class="actions">
  <%= link_to t(:'actions.show'), @mailbox %> |
  <%= link_to t(:'title.mailboxes'), mailboxes_path %>
</p>

app/views/mailboxes/index.html.erb
<% title t(:'title.mailboxes') %>
<%= render :partial => 'shared/search_form', :locals => { :domains => @domains, :target_url => mailboxes_path } %>
<%= paginate @mailboxes %>
<table>
<thead>
  <tr>
    <th><%= Mailbox.human_attribute_name("name") %></th>
    <th><%= Mailbox.human_attribute_name("active") %></th>
    <th><%= Mailbox.human_attribute_name("created_by") %></th>
    <th><%= Mailbox.human_attribute_name("updated_by") %></th>
  </tr>
</thead>
<tbody>
  <% for mailbox in @mailboxes %>
    <tr>
      <td><%= link_to mailbox, mailbox %></td>
      <td><%= mailbox.active %></td>
      <td><%= mailbox.created_by %></td>
      <td><%= mailbox.updated_by %></td>
      <td class="actions"><%= link_to t(:'actions.edit'), edit_mailbox_path(mailbox) %></td>
      <td class="actions"><%= link_to t(:'actions.delete'), mailbox, :confirm => t(:'actions.confirmdelete'), :method => :delete %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= paginate @mailboxes %>
<p class="actions"><%= link_to  t(:'resource.new', :model => Mailbox.model_name.human), new_mailbox_path %></p>

app/views/mailboxes/new.html.erb
<% title  t(:'resource.new', :model => Mailbox.model_name.human) %>

<%= render 'form' %>

<p class="actions"><%= link_to t(:'title.mailboxes'), mailboxes_path %></p>

app/views/mailboxes/show.html.erb
<% title Mailbox.model_name.human %>

<p>
  <strong><%= Mailbox.human_attribute_name("name") %>:</strong>
  <%= @mailbox.name %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("domain") %>:</strong>
  <%= @mailbox.domain %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("notes") %>:</strong>
  <%= @mailbox.notes %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("active") %>:</strong>
  <%= @mailbox.active %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("created_by") %>:</strong>
  <%= @mailbox.created_by %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("created_at") %>:</strong>
  <%= l(@mailbox.created_at, :format => :short) %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("updated_by") %>:</strong>
  <%= @mailbox.updated_by %>
</p>
<p>
  <strong><%= Mailbox.human_attribute_name("updated_at") %>:</strong>
  <%= l(@mailbox.updated_at, :format => :short) %>
</p>

<p class="actions">
  <%= link_to t(:'actions.edit'), edit_mailbox_path(@mailbox) %> |
  <%= link_to t(:'actions.delete'), @mailbox, :confirm => t(:'actions.confirmdelete'), :method => :delete %> |
  <%= link_to t(:'title.mailboxes'), mailboxes_path %>
</p>