config/routes.rb
MiniVmail::Application.routes.draw do
	
	get "downloads" => 'downloads#index' 

	get "downloads/export_relay_domains"
	get "downloads/virtual_aliases"
	get "downloads/relay_domains"
	get "downloads/relay_recipients"
	get "downloads/dovecot_auth"

	match "login" => 'user_sessions#new', :as => :login
	match "logout" => 'user_sessions#destroy', :as => :logout

	resource :user_session
	resources :users
	resources :forwards
	resources :mailboxes
	resources :domains

	get "welcome/index"
	get "welcome/initial_login"
	post "welcome/create_initial_login"

	root :to => "welcome#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Mini-VMail :: <%= yield(:title) %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
</head>

<body>
<div id="wrap">

<div id="leftside">
	<h1>Virtual Mail Administration</h1>
	<h2>Put your mail system on Rails!</h2>

	<div id="menu">
		<%= link_to t(:'title.home'), root_path %>
		<%= link_to t(:'title.domains'), domains_path if current_user.try(:admin) %>
		<%= link_to t(:'title.mailboxes'), mailboxes_path %>
		<%= link_to t(:'title.forwards'), forwards_path %>
		<%= link_to t(:'title.downloads'), :controller => "downloads" %>
		<% if current_user %>
			<%= link_to t(:'title.users'), users_path if current_user.admin %>
			<%= link_to t(:'actions.logout', :user =>current_user), logout_path %>
		<% else %>
			<%= link_to t(:'actions.login'), login_path %>
		<% end %>
	</div>
	
	<h3>Version info:</h3>
	<p><%= MiniVmail::VERSION::DISPLAY %></p>
</div>

<div id="extras">
	<%= render :partial => 'shared/extras' %>
	<%= render :partial => 'shared/downloads' %>
	
	<h2>Links</h2>
	<ul>
		<li><a href="http://www.postfix.org/" target="_blank">Postfix MTA</a></li>
		<li><a href="http://www.dovecot.org" target="_blank">Dovecot IMAP/ Server</a></li>
		<li><a href="http://www.postgresql.org/" target="_blank">PostgreSQL Database Server</a></li>
		<li><a href="http://www.rubyonrails.org/" target="_blank">Ruby on Rails Web Framework</a></li>
	</ul>
	<h3>Info</h3>
	<p>&copy; 2010 <a>Rainer Frey</a> | Design by Stylish <a href="http://www.stylishtemplate.com/" target="_blank">Website Templates</a></p>
</div>

<div id="content">
    <%= content_tag :h1, yield(:title) if show_title? %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
</div>

</div>
</body>
</html>